version: "3.9"

services:
  todo-api:
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile.buildkit}
      args:
        - revision=${REVISION:-1.0.0}
    image: ${IMAGE:-joergjo/java-boot-todo}
    ports:
      - "8080:8080"
      - "4004:4004"
    environment:
      - POSTGRESQL_FQDN=${POSTGRESQL_FQDN}
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-json-logging}
