version: "3.9"

services:
  todo-api:
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile.buildkit}
    image: java-boot-todo:${TAG:-latest}
    ports:
      - "8080:8080"
      - "4004:4004"
    environment:
      - POSTGRESQL_HOST=${POSTGRESQL_HOST}
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-json-logging}
