version: "3.9"

volumes:
  todo-data:

services:
  todo-api:
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile.buildkit}
    image: java-boot-todo:${TAG:-latest}
    ports:
      - "8080:8080"
      - "4004:4004"
    environment:
      - POSTGRESQL_FQDN=todo-db
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=pass@word1
      - SPRING_PROFILES_ACTIVE=local
    depends_on:
      - todo-db

  todo-db:
    image: postgres:${POSTGRES_TAG:-14-alpine}
    ports:
      - "5432:5432"
    volumes:
      - todo-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=pass@word1
      - POSTGRES_DB=demo
