FROM golang:1.22 AS builder

WORKDIR /build

# Only download Go modules (improves build caching)
COPY go.mod go.sum ./
RUN go mod download

# Copy our source code over and build the binary
COPY . .
RUN CGO_ENABLED=0 go build -ldflags '-s -w' -tags 'osusergo netgo' -o helloworld ./main.go

FROM alpine:latest AS final
EXPOSE 8000
WORKDIR /app
RUN apk --no-cache add ca-certificates
# Copy over the binary artifact
COPY --from=builder /build/helloworld .
ENTRYPOINT ["/app/helloworld"]
