version: "3.9"

services:
  todo-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${IMAGE:-joergjo/go-chi-todo}
    ports:
      - "8080:8080"
    environment:
      - PGHOST=${PGHOST}
      - PGPORT=${PGPORT:-5432}
      - PGSSLMODE=${PGSSLMODE:-require}
      - PGUSER=${AZURE_UPN}
      - PGDATABASE=${PGDATABASE:-todo}
      - TODO_DEBUG=${TODO_DEBUG:-true}
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
