version: "3.9"

networks:
  sb-todo:

services:
  sb-todo-api:
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile.buildkit}
    image: java-boot-todo-dd:${TAG:-latest}
    ports:
      - "8080:8080"
      - "4004:4004"
    environment:
      # Enable structured logging
      # - SPRING_PROFILES_ACTIVE=json-logging
      # Disable seeding test data
      # - SPRING_PROFILES_ACTIVE=prod
      - POSTGRESQL_HOST=${POSTGRESQL_HOST}
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - DD_ENV=${DD_ENV:-local}
      - DD_SERVICE=${DD_SERVICE:-sb-todo-api}
      - DD_VERSION=${DD_VERSION:-0.0.1}
      - DD_AGENT_HOST=dd-agent
      - DD_TRACE_AGENT_PORT=8126
      - DD_PROFILING_ENABLED=true
      - DD_TRACE_SAMPLE_RATE=1.0
    networks:
      - sb-todo
    depends_on:
      - dd-agent

  dd-agent:
    image: datadog/agent:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup/:ro
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_SITE=${DD_SITE:-datadoghq.eu}
      - DD_APM_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
    networks:
      - sb-todo
