name: Build and push container image for go-chi-todo
concurrency: go-chi-todo-${{ github.ref }}

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'go-chi-todo/**'
      - '!go-chi-todo/deploy/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Define Docker meta data
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/go-chi-todo
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./go-chi-todo
          file: ./go-chi-todo/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
